export const CHANGE_BASE_VALUE = "CHANGE_BASE_VALUE";
export const CHANGE_SCREEN = "CHANGE_SCREEN";
export const CHANGE_CATEGORY = "CHANGE_CATEGORY";
export const CHANGE_CURRENT_UNIT_INDEX = "CHANGE_CURRENT_INDEX";
